# Generated by Django 4.1.7 on 2023-03-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_joined_date_members_phon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='phon',
            new_name='phone',
        ),
    ]
